update typos and gramar for FR
prusa3d/Prusa-Firmware pull request #1182
Opened 2018-09-21 08:01 UTC by satblip

I have update french lang file to fix typos, gramar and add few translations

2018-09-23 09:56 UTC, 3d-gussner requested changes
You need to consider the max. characters to be used and the rows.
The display will split the message into rows at the word that hits the limit.

Some messages are limited to c=17 (smaller than c=20) due to multiple information on the LCD or additional values behind it. If you expend that limit this may be unreadable.

Just a tip, before you post language PRs it is good if you compile your changes and review them on your printer LCD. This way the chances are higher to get it merged.

2018-09-23 09:56 UTC, 3d-gussner commented on lang/lang_en_fr.txt
> +"Ventilation extrudeur:"
This is too long as shown above c=18 r=0 means max. 18 characters and one row

2018-09-23 09:56 UTC, 3d-gussner commented on lang/lang_en_fr.txt
> +"La reponse du capteur de filament est pauvre, le desactiver ?"
This is too long as shown above c=20 r=2 means max. 20 characters per row and max 2 rows. This translation will use 3 rows

2018-09-23 09:56 UTC, 3d-gussner commented on lang/lang_en_fr.txt
> +"Changer le filament"
This might not fit on the LCD screen, did you compile and test this change?

2018-09-23 09:56 UTC, 3d-gussner commented on lang/lang_en_fr.txt
> +"Le changement est correct ?"
too long, see above

2018-09-23 09:56 UTC, 3d-gussner commented on lang/lang_en_fr.txt
> +"Changement du filament!"
too long, see above

2018-09-23 09:56 UTC, 3d-gussner commented on lang/lang_en_fr.txt
> +"Ventilateur tete gauche?"
will use two rows, see above

2018-09-23 09:56 UTC, 3d-gussner commented on lang/lang_en_fr.txt
> +"Retirer le filament 1"
too long, see above

2018-09-27 06:19 UTC, satblip commented
Ok @3d-gussner thanks for remarks, I'll change them soon to fit the needs

2018-09-27 08:05 UTC, 3d-gussner commented
@satblip you should check all messages for these limits. Also compare it to the latest version from Prusa. As said if you compile it and test your changes on your printer the chances are higher to get your pull request pulled.
I had some in the past bit too long messages and they messed up the results on the LCD :-) also splitting words may help to make long messages easier to read, don't know if that is a common thing in French but in German splitting long words is quite often used in newspapers to fit the columns they are restricted to.
I hope I learned my lesson.

2019-10-25 17:14 UTC, 3d-gussner commented
@satblip I think these have been fixed, can you review your PR and if it is not needed anymore please close it.

2020-03-14 13:07 UTC, closed without merging

2020-03-14 13:08 UTC, satblip commented
@3d-gussner indeed that has moved forward, thanks for the follow up!