Implement M405/M406 to enable/disable the filament sensor
prusa3d/Prusa-Firmware pull request #1447
Opened 2019-01-07 18:54 UTC by Commod0re

basic implementation of M405 and M406. It compiles but I have not tested it other than that yet

2019-12-02 14:06 UTC, 3d-gussner commented on Firmware/Marlin_main.cpp
> +#endif
Missing `break;` at the end of M406

2019-12-30 04:49 UTC, Commod0re commented on Firmware/Marlin_main.cpp
> +#endif
nice catch; fixed!

2020-05-12 20:32 UTC, Commod0re commented
revisiting this: I've updated my PR to resolve the merge conflict, maybe this can get looked at again soon

2023-08-02 10:57 UTC, 3d-gussner requested changes

2023-08-02 10:57 UTC, 3d-gussner commented on Firmware/Marlin_main.cpp
> +        fsensor_enable();
it is now `fsensor.setEnabled(1);`

2023-08-02 10:57 UTC, 3d-gussner commented on Firmware/Marlin_main.cpp
> +        fsensor_disable();
Use `fsensor.setEnabled(0);`

2023-08-02 10:57 UTC, 3d-gussner commented on Firmware/Marlin_main.cpp
> +#ifdef FILAMENT_SENSOR
Add the doxygen documentation for `M405` and `M406`

similar to
https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/Marlin_main.cpp#L7423-L7434

2023-08-10 13:17 UTC, DRracer approved these changes

2023-08-11 06:42 UTC, leptun approved these changes

2023-08-11 06:48 UTC, DRracer approved these changes

2023-08-11 07:02 UTC, merged