Fan check error fix
prusa3d/Prusa-Firmware pull request #1889
Opened 2019-05-31 09:37 UTC by DRracer

When the user didn't resolve the fan error and tried to resume printing, the printer could get into an undefined state.

2019-05-31 13:42 UTC, mkbel requested changes

2019-05-31 13:42 UTC, mkbel commented on Firmware/pins_Einsy_1_0.h
> +#define LCD_BL_PIN          5   //backlight control pin
Is not related to fan check error fix

2019-06-03 07:03 UTC, DRracer commented on Firmware/pins_Einsy_1_0.h
> +#define LCD_BL_PIN          5   //backlight control pin
reverted...

2019-06-06 13:05 UTC, mkbel commented on Firmware/temperature.cpp
> +void fanSpeedErrorBeep(const char *serialMsg, const char *lcdMsg){
It doesn't need to be global function.

2019-06-06 13:51 UTC, mkbel approved these changes

2019-06-06 13:52 UTC, merged