#2093 - Relocate sheet menu, show sheet on info screen
prusa3d/Prusa-Firmware pull request #2146
Opened 2019-08-29 22:10 UTC by vintagepc

-Sheet is shown instead of percentage done either if idle, or during
print preheat. (Both consume exactly 7 characters)
-Relocated sheet menu to below SD menu for additional visibility to
current sheet.

2019-08-30 09:31 UTC, DRracer commented
@vintagepc  Good ideas, thanks for your PR. For now the sheets menu will be like we have it in #2145, but I really like your idea about the status screen showing sheet name instead of percentage in idle. I'll talk about it with our content guys.

2019-08-30 11:20 UTC, vintagepc commented
That's fair, looks like we essentially did the same thing for the menu move (though I didn't hide mine if there's only a single sheet in use)

2019-08-30 15:05 UTC, vintagepc commented
I'll merge to synchronize with #2145's changes and I realized I can also toss in a fix for #2089 which should be an easy fix.

2019-08-30 23:19 UTC, vintagepc commented
Fixed #2089, merged Mk3

2019-09-10 12:31 UTC, DRracer commented
@vintagepc I'm marking this as 3.9.x but please note we are still to gain some significant user response about the sheets, so this PR may require some more changes

2019-09-10 13:04 UTC, vintagepc commented
Understood, I'm hoping to keep it maintained as new features are added to the firmware.

2019-10-07 20:51 UTC, vintagepc commented
I merged 3.8.1-RC1 into my local branch which has this applied and it still functions as expected :+1:

2019-11-15 11:37 UTC, DRracer requested changes
besides the cursor '^' change we are ready to merge this, please finish the PR as requested, thank you

2019-11-15 11:37 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    if (menuData->selected>0)
please remove this part from the PR. We know you'd like the cursor to move (and not duplicate) under the edited character, but AFAIK there is another PR for that, isn't it?

2019-11-15 12:19 UTC, vintagepc commented on Firmware/ultralcd.cpp
> +    if (menuData->selected>0)
Not to my knowledge, I filed it as a separate issue in #2089 but did not make a separate branch or PR for this and a quick search in open requests did not turn up any results. 

If you'd still like me to remove it then I'm happy to do so, just say the word.

2019-11-15 13:54 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    if (menuData->selected>0)
please do so

2019-11-15 13:59 UTC, vintagepc commented on Firmware/ultralcd.cpp
> +    if (menuData->selected>0)
Done

2019-11-15 15:07 UTC, DRracer approved these changes

2019-11-15 15:07 UTC, merged

2019-11-18 16:03 UTC, vintagepc commented
I guess I can cross  "Earn 'contributor' badge for Prusa Github" off my bucket list now  😄