dialogs' layouts fixes + FR polished
prusa3d/Prusa-Firmware pull request #2202
Opened 2019-09-13 14:56 UTC by DRracer

dialogs' layouts fixes (support menu dlgs, statistics etc.)
French translation polished

2019-09-17 16:02 UTC, mkbel requested changes

2019-09-17 16:02 UTC, mkbel commented on Firmware/menu.cpp
> +        lcd_printf_P(menu_fmt_float13off, chr, str, _i(" [off]"));
I don't see menu_fmt_float13off change in this commit to match change from string from RAM to PROGMEM.

2019-09-17 16:02 UTC, mkbel commented on Firmware/menu.cpp
> +        lcd_printf_P(menu_fmt_float13off, chr, str, _i(" [off]"));
Fixed in:
14933f6b0e26894789af1284ad1b529f65a9e508

Fix. Sound [assist], Z-probe [5], menu_fmt_float13off format for last
string parameter from PROGMEM

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +static void pgmtext_with_colon(const char *ipgmLabel, char *dst, uint8_t dstSize){
Function parameters not documented.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(_i("Nozzle FAN"), nozzle, 12);
Do not use hardcoded constant if you can compute it. sizeof(nozzle)/sizeof(nozzle[0])

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(_i("Print FAN"), print, 12);
Do not use hardcoded constant if you can compute it. sizeof(print)/sizeof(print[0])

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    char nozzle[12], print[12];
Declaring more variables in one line is not recommended especially for pointer types.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(ipgmLabel, tmp, 15);
Do not use hardcoded constant if you can compute it. sizeof(tmp)/sizeof(tmp[0])

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    for(; i < dstSize - 2; ++i){ // 1 byte less than buffer, we'd be adding a ':' to the end
Comment is misleading. Do you mean 2 bytes less than buffer, we'd be adding a ':' and '\0' ?

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    dst[dstSize-1] = 0;         // terminate the string properly
If you assign '\0', you can save the comment, as purpose  would be clear from code.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    lcd_printf_P(PSTR("%S\n" " %-16.16S%-3d\n" " %-16.16S%-3d"), _i("Last print failures"), _i("MMU fails"), fails, _i("MMU load fails"), load_fails);
Length hint for translators missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    lcd_printf_P(failStatsFmt, _i("Total failures"), _i("Power failures"), power, _i("Filam. runouts"), filam, _i("Crash"), crashX, crashY);
Length hint for translators missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    lcd_printf_P(failStatsFmt, _i("Last print failures"), _i("Power failures"), power, _i("Filam. runouts"), filam, _i("Crash"), crashX, crashY);
Length hint for translators missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +static void lcd_menu_temperatures_line(const char *ipgmLabel, int value){
Function parameters not documented.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    lcd_menu_temperatures_line( _i("Ambient"), (int)current_temperature_ambient );
Length hint for translators is missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +    lcd_menu_temperatures_line( _i("PINDA"), (int)current_temperature_pinda );
Length hint for translators is missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
>  		),_i("Filament used"), _met, _i("Print time"), _h, _m, _s);
Length hint for translators is missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
>  		), _i("Total filament"), _filament_m, _i("Total print time"), _days, _hours, _minutes);
Length hint for translators is missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +	 _i("Slight skew:"), _deg(bed_skew_angle_mild),
Length hint for translators is missing.

2019-09-17 16:02 UTC, mkbel commented on Firmware/ultralcd.cpp
> +	 _i("Severe skew:"), _deg(bed_skew_angle_extreme)
Length hint for translators is missing.

2019-09-17 17:15 UTC, 3d-gussner commented
@DRracer few of the comments from @mkbel could be solved if you pull the https://github.com/DRracer/Prusa-Firmware/tree/translations-doc as there are "Length hint for translators."

2019-09-17 17:20 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(_i("Nozzle FAN"), nozzle, 12);
@mkbel If you look into https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L1684 then you see that it has to do with placing the message correctly. As translations of a word or phrase can differ from English, i think it makes sense to "hardcode" it here.

2019-09-17 17:20 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(_i("Print FAN"), print, 12);
@mkbel See my comment above

2019-09-17 17:24 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +	 _i("Severe skew:"), _deg(bed_skew_angle_extreme)
see https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L3012

2019-09-17 17:24 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +	 _i("Slight skew:"), _deg(bed_skew_angle_mild),
see https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L3011

2019-09-17 17:24 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
>  		), _i("Total filament"), _filament_m, _i("Total print time"), _days, _hours, _minutes);
That one I also missed in https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L2858

2019-09-17 17:24 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
>  		),_i("Filament used"), _met, _i("Print time"), _h, _m, _s);
see https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L2836

2019-09-17 17:24 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +    lcd_menu_temperatures_line( _i("PINDA"), (int)current_temperature_pinda );
This have been documented in https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L1961 . just needs a merge.

2019-09-17 17:24 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(ipgmLabel, tmp, 15);
See my comment above

2019-09-17 17:25 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +    lcd_printf_P(PSTR("%S\n" " %-16.16S%-3d\n" " %-16.16S%-3d"), _i("Last print failures"), _i("MMU fails"), fails, _i("MMU load fails"), load_fails);
See https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L1780

2019-09-17 17:26 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +    lcd_printf_P(failStatsFmt, _i("Total failures"), _i("Power failures"), power, _i("Filam. runouts"), filam, _i("Crash"), crashX, crashY);
See https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L1826

2019-09-17 17:26 UTC, 3d-gussner commented on Firmware/ultralcd.cpp
> +    lcd_printf_P(failStatsFmt, _i("Last print failures"), _i("Power failures"), power, _i("Filam. runouts"), filam, _i("Crash"), crashX, crashY);
See https://github.com/DRracer/Prusa-Firmware/blob/translations-doc/Firmware/ultralcd.cpp#L1849

2019-09-17 18:13 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(_i("Nozzle FAN"), nozzle, 12);
@mkbel I'd rather define a static const int something than doing sizeof(nozzle)/sizeof(nozzle[0]), but you are right. Hardcoding 3x the same constant isn't a final code. @3d-gussner is correct, the input text will be cut to 11 characters max no matter what comes from the translation engine

2019-09-17 18:15 UTC, DRracer commented on Firmware/ultralcd.cpp
>  		), _i("Total filament"), _filament_m, _i("Total print time"), _days, _hours, _minutes);
@3d-gussner we definitely shall merge the translation-doc ASAP, there is so much work that will improve this.

2019-09-18 09:51 UTC, DRracer commented on Firmware/ultralcd.cpp
> +static void pgmtext_with_colon(const char *ipgmLabel, char *dst, uint8_t dstSize){
@mkbel will be added

2019-09-18 09:57 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(_i("Nozzle FAN"), nozzle, 12);
@mkbel will be fixed in next commit

2019-09-18 09:58 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    char nozzle[12], print[12];
@mkbel in this case it is reasonably readable

2019-09-18 09:58 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    pgmtext_with_colon(ipgmLabel, tmp, 15);
@mkbel will be fixed in next commit

2019-09-18 10:02 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    for(; i < dstSize - 2; ++i){ // 1 byte less than buffer, we'd be adding a ':' to the end
@mkbel will be fixed in next commit

2019-09-18 10:02 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    dst[dstSize-1] = 0;         // terminate the string properly
@mkbel will be fixed in next commit

2019-09-18 10:03 UTC, DRracer commented on Firmware/ultralcd.cpp
> +static void lcd_menu_temperatures_line(const char *ipgmLabel, int value){
@mkbel will be fixed in next commit

2019-09-19 14:33 UTC, mkbel approved these changes

2019-09-19 14:33 UTC, merged