Allow all microstep resolutions for all axes
prusa3d/Prusa-Firmware pull request #3005
Opened 2021-01-29 18:22 UTC by wavexx

The current FW limits the microstep resolution depending on the motor.
XYZ are limited to 32 usteps, while E requires 8 or higher. This is sensible, but prevents debugging or custom configurations.

This PR simplifies the check in order to require a valid µstep resolution without imposing any restriction on the resolution.
Some combinations might not be that useful or work properly, but I believe it's up to the user to decide.

2021-02-02 08:23 UTC, DRracer commented
_... it's up to the user to decide._ ... that's a fair point, however our FW should be safe for general usage/users in the first place. Allowing too many degrees of freedom will make the maintainability of the FW harder, especially in terms of testing.

We are still thinking about merging this, however some discussion of potential impact on user experience and the printers themselves shall be done first.

2021-03-09 14:13 UTC, bubmann commented
> 
> 
> _... it's up to the user to decide._ ... that's a fair point, however our FW should be safe for general usage/users in the first place. Allowing too many degrees of freedom will make the maintainability of the FW harder, especially in terms of testing.
> 
> We are still thinking about merging this, however some discussion of potential impact on user experience and the printers themselves shall be done first.

maybe an "advanced/expert" menu can be fitted into the eeprom? just like in the slicer

2022-02-06 07:50 UTC, leptun approved these changes

2022-02-09 06:48 UTC, DRracer commented on Firmware/Marlin_main.cpp
> +				bool res_valid = res_new > 0 && res_new <= 256 && !(res_new & (res_new - 1)); // must be a power of two
nice trick :+1: 
`!(res_new & (res_new - 1)); // must be a power of two`

2022-02-09 06:52 UTC, DRracer requested changes
Please add some #define to enable additional ustep resolutions.
`#ifdef ALLOW_ALL_MRES` or something similar
Experienced users can then enable such a mode + recompile the FW while others stay on the safe side with the previous explicit list of supported mres.

2022-02-09 07:12 UTC, DRracer commented
> maybe an "advanced/expert" menu can be fitted into the eeprom? just like in the slicer

@bubmann I'm afraid adding a menu item + related infrastructure to enable runtime switching between the safe/advanced mres check is just way too heavy for our limited CPU space. It can be done, but we'd like to devote the remaining few KB of memory to more important features.

2022-02-09 09:31 UTC, leptun commented
Wow.
```
Sketch uses 229716 bytes (90%) of program storage space. Maximum is 253952 bytes.
Global variables use 6436 bytes of dynamic memory.
```
The ram usage has gone down significantly with the optimizations PRs. (756B of ram saved overall). Keep in mind that the base of this branch is from many releases ago. But still, the efficiency was grearly improved in the meantime.

2022-02-09 09:32 UTC, leptun approved these changes
Requested changes have been done. Approving again

2022-02-09 12:48 UTC, DRracer approved these changes
:+1:

2022-02-09 12:48 UTC, merged