:construction:  WIP: Prepare release
prusa3d/Prusa-Firmware pull request #3043
Opened 2021-02-25 11:23 UTC by 3d-gussner

- [x] Fix missing/duplicate translations
- [ ] Update translation po files
- [ ] Update RepRap Wiki

2021-03-19 15:25 UTC, awenelo requested changes

2021-03-19 15:25 UTC, awenelo commented on lang/po/Firmware_fr.po
> +msgstr "Bonjour, je suis votre imprimante Original Prusa i3. Je vais vous accompagner au cours d'un bref processus de reglage, qui permettra de calibrer le Z-axis. Apres cela, tout sera pret pour imp
```suggestion
msgstr "Bonjour, je suis votre imprimante Original Prusa i3. Je vais vous accompagner au cours d'un processus bref de reglage pour calibrer le Z-axis. Apres cela, tout sera pret pour imprimer."
```

##### `bref processus` -> `processus bref`
`bref` is describing the length, not the size of the process, and should come after the noun.

##### `processus de relage, qui permettra de calibrer` -> `processus de relage pour calibrer`
`qui permettra de calibrer` sounds like you're saying `One of the things you can do in this calibration process is calibrate the Z-axis, but it's not necessary for printing`. If the process is to calibrate the Z-axis and it's necessary to print, then you should say `pour calibrer`.

2021-04-04 05:24 UTC, 3d-gussner commented
@DRracer can you try to fix Czech translations?
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_cz.txt#L141-L143
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_cz.txt#L865-L867
```
count=364
offs=744
size=10202
lang=cz
Start cz lang-check
[E]: Text "Kalibruji vychozi poz." is longer then definiton on line 141 rows diff=1

[E]: Text "Stisknete hl. tlacitko" is longer then definiton on line 865 rows diff=1

End cz lang-check
```

2021-04-04 05:32 UTC, 3d-gussner commented
Can anyone try to fix Spanish translations?
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_es.txt#L141-L143
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_es.txt#L313-L315
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_es.txt#L321-L323
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_es.txt#L405-L407
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_es.txt#L537-L539
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_es.txt#L641-L643
https://github.com/3d-gussner/Prusa-Firmware/blob/PFW-1189/lang/lang_en_es.txt#L1293-L1295

```
count=364
offs=744
size=11221
lang=es
Start es lang-check
[E]: Text "Calibrar posicion inicial" is longer then definiton on line 141 rows diff=1

[E]: Text "ERROR: El sensor de filamento no responde, por favor comprueba la conexion." is longer then definiton on line 289 rows diff=1

[E]: Text "Estadistica de fallos MMU" is longer then definiton on line 313 rows diff=1

[E]: Text "Estadistica de fallos" is longer then definiton on line 321 rows diff=1

[E]: Text "Ventiladores frontal/izquierdo" is longer then definiton on line 405 rows diff=1

[E]: Text "Correccion de Linealidad" is longer then definiton on line 537 rows diff=1

[E]: Text "Fallo de energia en MMU" is longer then definiton on line 641 rows diff=1

[E]: Text "Distancia en Y desde el min" is longer then definiton on line 1293 rows diff=1

End es lang-check

```

2021-04-26 13:06 UTC, closed without merging