:construction: WIP: Improve language scripts
prusa3d/Prusa-Firmware pull request #3342
Opened 2022-01-07 13:56 UTC by 3d-gussner

- [x] Add syntax checks for translations in `lang-check.py`
- [ ] Update documentation in scripts

2022-01-10 14:17 UTC, 3d-gussner commented
@wavexx Could you please review the changes I made in `lang-check.py`?

2022-01-30 14:48 UTC, 3d-gussner commented
@AtillaSVK Can you please review/comment/approve? https://github.com/prusa3d/Prusa-Firmware/pull/3342/files#diff-a24289c9ad15eb88af1103e3112ffcd9dca5beb53390bd094ddac06fa1e792f3R238-R275

2022-02-03 06:39 UTC, DRracer commented on .gitignore
> +tools/lib/.DS_Store
ideally add a newline at the end of this file

2022-02-03 06:42 UTC, DRracer commented on Firmware/messages.c
> +const char MSG_UNLOAD_FILAMENT[] PROGMEM_I1 = ISTR("Unload filament"); ////c=18
:thinking: are you sure the original comment is no longer valid - i.e. the text is not used for the MMU as well?
In such a case the `c=16` would make sense

2022-02-03 06:43 UTC, DRracer commented on Firmware/messages.c
> +const char MSG_UNLOAD_FILAMENT[] PROGMEM_I1 = ISTR("Unload filament"); ////c=18
Oh, it has been used for the SNMM and now it is "guarded" with a compile error (as the SNMM has been broken for a long time)

2022-02-03 06:52 UTC, DRracer commented on lang/lang-import.sh
> +#check for nonasci characters excpet HD44780 ROM A00 'äöüß'
/nitpick/: typo `excpet` -> `except`

2022-02-03 06:56 UTC, DRracer commented on lang/progmem.sh
>  exit 0
no newline at end of file

2022-02-03 06:56 UTC, DRracer commented on lang/textaddr.sh
>  exit 0
no newline at end of file

2022-02-03 07:00 UTC, DRracer requested changes
just a few minor comments, please have a look at them

2022-02-03 07:21 UTC, DRracer approved these changes
:+1:

2022-02-03 07:21 UTC, merged