build: Set all version data based on git tags
prusa3d/Prusa-Firmware pull request #3665
Opened 2022-10-06 12:02 UTC by wavexx

Drop the ALPHA/BETA/custom version handling. Set the version string and firmware date based on the current git tree which has all the required details.

- Use the short HEAD commit hash as the default suffix. This also overrides the old "build number" which is essentially useless for reproducibility purposes. A truncated 16bit version of the hash is now also used in its place in the eeprom.
- Use the output of "describe" as the full version string.
- Use the HEAD commit timestamp as SOURCE_DATE_EPOCH.

With the new structure it's possible to checkout an old tree and get a reproducible artifact. The Configuration.h header provides fallback values whenever git is not available (for example, for zip archives).

In order to get meaningful description we need to create dummy annotated tags when the version number is bumped. After this is done (for example, tagging 9f1f396c18ecc91230959c2b47f6271824398fed with t3.13), the resulting version would look something like:

```
-- Project version ...........: 3.13.0
-- Project version suffix ....: 49bc78425
-- Project version description: t3.13-431-g49bc78425
```

2022-10-06 12:17 UTC, vintagepc approved these changes

2022-10-19 07:07 UTC, 3d-gussner requested changes
We have to keep the Build number

2022-10-19 07:07 UTC, 3d-gussner commented on Firmware/Configuration.h
> +#ifndef FW_FLAVERSION
Please keep `#define FW_COMMIT_NR 4987`

2022-10-19 09:23 UTC, wavexx commented on Firmware/Configuration.h
> +#ifndef FW_FLAVERSION
I will add the ability to include a build number via cmake, but not in the sources

2023-08-14 11:12 UTC, 3d-gussner commented
https://github.com/prusa3d/Prusa-Firmware/pull/4044 is based on this PR setting it to draft and we may close it in favor of the PR 4044

2023-09-04 08:08 UTC, 3d-gussner commented
Obsolete by https://github.com/prusa3d/Prusa-Firmware/pull/4366

2023-09-04 08:08 UTC, closed without merging