Disable `Error:` messages for MMU2 errors
prusa3d/Prusa-Firmware pull request #3718
Opened 2022-10-26 19:08 UTC by 3d-gussner

OctoPrint by default reacts with emergency stop on this

2022-10-26 20:50 UTC, gudnimg approved these changes

2022-10-27 05:18 UTC, DRracer requested changes
:thinking: I don't like removing the LogErrorEvent ... 
We can change the way errors are propagated from the MMU state machine, but they are still errors. That is unrelated to the way the errors are to be represented on the serial line due to some 3rd party programs compatibility.

So I propose to keep LogErrorEvent (and its _P variant) but change the way the errors are printed.

2022-10-28 06:34 UTC, DRracer approved these changes

2022-10-29 19:38 UTC, gudnimg approved these changes
Re-approving :)

2022-11-03 11:08 UTC, DRracer approved these changes

2022-11-03 11:09 UTC, merged