PFW-1425 Move `Load to Extruder` to `Settings` menu
prusa3d/Prusa-Firmware pull request #3739
Opened 2022-11-06 15:49 UTC by gudnimg

I also combined all the MMU menus within Settings under a single `if (eeprom_read_byte((uint8_t *)EEPROM_MMU_ENABLED))` this saves a little bit of flash memory.

Change in memory:
Flash: -24 bytes
SRAM: 0 bytes

2022-11-06 16:16 UTC, gudnimg commented
@3d-gussner I wasn't sure about the languages part. PFW-1425 tickets states we should change the message `"Load to extruder" `to `"Loading test"`.

I'm not sure which script is used to update this in the language files: `#: ../../Firmware/messages.cpp:57 ../../Firmware/ultralcd.cpp:5546`

I see most of the script are based around Unix. I will try to create a Python script which will work on Windows as well.

2022-11-06 18:48 UTC, gudnimg commented
@3d-gussner I did my best to update the languages. Created a new script `update_po.py` which can be run on Windows. (I couldn't use `update_po.sh`)

Also updated `lang_extract.py` to work on Windows. I haven't tested on Unix.

2022-11-06 19:20 UTC, gudnimg commented on lang/po/Firmware_cs.po
> +" tlacitkem."
There are some minor differences in the `.po` files with long strings. I could not fix this by adjusting the string width. So I’m not sure if this is a mistake in the `.po` file or how to resolve it if it is a mistake in `polib` side in Python.

2022-11-09 13:45 UTC, DRracer requested changes
@gudnimg please beware:
`eeprom_read_byte((uint8_t *)EEPROM_MMU_ENABLED)`
is not the same as:
`MMU2::mmu2.Enabled()`

The EEPROM flag means, that the printer should be actively looking for the MMU.
`MMU2::mmu2.Enabled()` means, that the printer and MMU established communication succesfully - i.e. the printer runs in MMU mode -> unlocking the othewise hidden items of the menu.

I think most of the MMU-related menu items (except for the MMU Enable and Reset) should be displayed only if the MMU is communicating with the printer.

2022-11-10 17:25 UTC, gudnimg commented
> @gudnimg please beware: `eeprom_read_byte((uint8_t *)EEPROM_MMU_ENABLED)` is not the same as: `MMU2::mmu2.Enabled()`
> 
> The EEPROM flag means, that the printer should be actively looking for the MMU. `MMU2::mmu2.Enabled()` means, that the printer and MMU established communication succesfully - i.e. the printer runs in MMU mode -> unlocking the othewise hidden items of the menu.
> 
> I think most of the MMU-related menu items (except for the MMU Enable and Reset) should be displayed only if the MMU is communicating with the printer.

Good point. I hadnt considered that difference.

2022-11-15 10:16 UTC, 3d-gussner submitted a review, later dismissed

2022-11-15 10:16 UTC, 3d-gussner commented on lang/update_po.py
> +# Portable script to update po files on most platforms
`#!/usr/bin/env python3` is missing at the beginning for Linux

2022-11-15 15:54 UTC, DRracer commented on Firmware/ultralcd.cpp
>      if (eeprom_read_byte((uint8_t *)EEPROM_MMU_ENABLED))
again - SpoolJoin, Cutter, MMU mode and Load test should be available only if (MMU2::mmu2.Enabled())

2022-11-15 15:55 UTC, DRracer commented on Firmware/ultralcd.cpp
> +    if (MMU2::mmu2.Enabled())
:+1: 

but the Reset MMU option should be probably available even when the MMU is not communicating

2022-11-15 16:16 UTC, DRracer approved these changes

2022-11-15 16:32 UTC, merged