MK3: Fix `M862.4` with [strict] mode
prusa3d/Prusa-Firmware pull request #3805
Opened 2022-12-06 12:28 UTC by 3d-gussner

Max 8 flavor versions
Minor changes: easier to un-comment serial debug

Tested with MK404
Settings -> HW Setup -> Checks -> Firmware set to `[warn]`
- [X] Send `M862.4 P3.11.0` nothing happens as FW is newer
- [X] Send `M862.4 P3.13.0-RC1` warning shown on LCD to continue with print
- [X] Send `M862.4 P3.13.0` warning shown on LCD to continue with print

Settings -> HW Setup -> Checks -> Firmware set to `[strict]`
- [X] Send `M862.4 P3.11.0` nothing happens as FW is newer
- [X] Send `M862.4 P3.13.0-RC1` warning shown on LCD and print canceled 
- [X] Send `M862.4 P3.13.0` warning shown on LCD and print canceled

ToDo's:
- [ ] Cherry-pick to MK3_3.12

2022-12-07 13:33 UTC, vintagepc commented on Firmware/util.cpp
> +    SERIAL_ECHO(eeprom_read_word((uint16_t *)EEPROM_FIRMWARE_VERSION_FLAVOR));
... why are we reading the version from EEPROM instead of PROGMEM? Doesn't this have a risk of being wrong?

2022-12-07 17:50 UTC, wavexx requested changes

2022-12-07 17:50 UTC, wavexx commented on Firmware/util.cpp
> +    if ((nCompareValueResult < COMPARE_VALUE_EQUAL) && (oCheckVersion == ClCheckVersion::_Warn || oCheckVersion == ClCheckVersion::_Strict))
It looks like to me the original idea of "strict" was "exactly the reversion", at least to the code.
I think we can change this to:

```
if (nCompareValueResult <= COMPARE_VALUE_EQUAL)
```

since we handle _None above, and everything else is handled later.

2022-12-07 17:50 UTC, wavexx commented on Firmware/util.cpp
> +    if ((nCompareValueResult < COMPARE_VALUE_EQUAL) && (oCheckVersion == ClCheckVersion::_Warn || oCheckVersion == ClCheckVersion::_Strict))
We also have exactly the same

```
if (nGcodeLevel == (uint16_t)GCODE_LEVEL)
```

that we could change to:

if (nGcodeLevel <= (uint16_t)GCODE_LEVEL)

at line 424 (can't attach a comment)

2022-12-09 12:32 UTC, wavexx commented
Was this re-tested?

2022-12-12 11:22 UTC, 3d-gussner commented
> Was this re-tested?

Retested on MK404:
All conditions working correctly.

- [X] Strict Only triggers when gcode sends newer firmware
- [X] Warn Only triggers when gcode sends newer firmware  
- [X] None ignores any `M862.4 Px.y.z-abc` gcode

2022-12-12 11:38 UTC, wavexx approved these changes

2022-12-12 11:38 UTC, merged