Add 'Yes' and 'No' choices to messages like: "G-code sliced for a different printer type. Continue?"
prusa3d/Prusa-Firmware pull request #3821
Opened 2022-12-13 19:19 UTC by gudnimg

Fixes a minor thing that annoys me personally. If I get the this screen accidentally, then clicking the knob can't cancel the print.

This PR adds 'Yes' and 'No' choices for all the warning screens and we save flash too :)

Change in memory:
Flash: -98 bytes
SRAM: 0 bytes

2022-12-13 22:07 UTC, wavexx approved these changes
I hated the check so I disabled it. This looks a much better solution :))

2022-12-16 15:26 UTC, DRracer requested changes
The message timeout option is missing from the new implementation. It should be kept.

2022-12-16 16:21 UTC, gudnimg commented
> The message timeout option is missing from the new implementation. It should be kept.

`extern uint8_t lcd_show_fullscreen_message_yes_no_and_wait_P(const char *msg, bool allow_timeouting = true, uint8_t default_selection = LCD_MIDDLE_BUTTON_CHOICE);`

The timeout is on by default. See `allow_timeouting`. The timeout is currently set to 30 seconds which the same value as before.

```
#define LCD_TIMEOUT_TO_STATUS 30000ul //!< Generic timeout to status screen in ms, when no user action.
if (allow_timeouting && _millis() - previous_millis_cmd > LCD_TIMEOUT_TO_STATUS) {
    return LCD_BUTTON_TIMEOUT;
}
```

2022-12-29 19:47 UTC, gudnimg commented
Timeout seems to work 👍 I would approve if this wasn't my PR :)

2022-12-29 20:01 UTC, leptun approved these changes

2022-12-30 10:47 UTC, DRracer commented on Firmware/ultralcd.cpp
> +exit:
it would be better to use some RAII pattern, but the compiler makes the jmp instructions anyway :wink: , so I don't complain

2022-12-30 10:48 UTC, DRracer approved these changes
approving now

2022-12-30 11:49 UTC, merged