cmdqueue improvements
prusa3d/Prusa-Firmware pull request #3823
Opened 2022-12-14 10:27 UTC by wavexx

:warning: This is stacked on top of #3822 

With #3822 I realized we already drop the checksum from the command queue, so I extended this to line numbers. Turns out this has *numerous* benefits.

- More space for the cmdqueue for serial commands
- No exceptions for the horrible PRUSA/related commands (they now parse fine with line numbers)
- No more scanning for the first gcode: it is always expected as the first entry
- No more ambiguous parsing: this reduces the overhead we had for M0/M1/M117 in addition to actually being more robust to serial noise.

Turns out we never supported checksums without line numbers, but according to https://reprap.org/wiki/G-code#.2A:_Checksum this *can* be possible?

There's also no clear indication as to leading whitespace needs to be supported or not. It looks like many commands assumed no initial whitespace should ever exist. The checksum calculation includes the leading whitespace into account.

In this PR extra whitespace is supported after the line number, but not immediately at the start. It would be easy to drop this as well. The question is whether we should? @3d-gussner

2022-12-14 12:26 UTC, wavexx commented
> @wavexx The only fault I can see with this is what would happen with a gcode file that was uploaded to the SD over usb. I'm pretty sure in the past the line numbers would get saved to the file on the SD, but with $ instead of N. If that is the case, then all lines will be parsed incorrectly. I played a few months ago with this, but I don't remember if I made it so it doesn't save those line numbers to SD. Can you try uploading a file to the SD and check how it looks like?

2022-12-15 07:07 UTC, wavexx commented
Leading whitespace is now handled, so it should show no behavioral differences.

2022-12-22 12:34 UTC, leptun requested changes
I tested the USB upload feature and the parsing is indeed correct. I also checked some other commands over USB and they worked correctly. I also ran a very short gcode file from the SD and that finished correctly as well.

However, there seem to be some issues with M0/M1. See the following log. I was no longer able to send any command to the printer after M0, even though it sent back "ok". Notice also the corrupted serial message.
```
Send: M0
Recv: LCD status changed
Recv: T:22.4 /0.0 B:23.3 /0.0 T0:22.4 /0.0 @:0 B@:0 P:24.0 A:31.7
Recv: echo:busy: paused for user
Printer seems to support the busy protocol, will adjust timeouts and set busy interval accordingly
Recv: T:22.4 /0.0 B:23.0 /0.0 T0:22.4 /0.0 @:0 B@:0 P:23.9 A:31.8
Recv: LCD status changed
Recv: ok
Send: M113 S2
Recv: oáT:22.5 /0.0 B:23.2 /0.0 T0:22.5 /0.0 @:0 B@:0 P:24.1 A:31.5
Recv: T:22.5 /0.0 B:22.9 /0.0 T0:22.5 /0.0 @:0 B@:0 P:24.0 A:31.7
Recv: T:22.4 /0.0 B:23.2 /0.0 T0:22.4 /0.0 @:0 B@:0 P:24.2 A:31.8
```
M117 is also broken. I sent "M117 test" to the printer and I saw "117 test" on the lcd. This is not correct

2022-12-22 14:11 UTC, wavexx commented
Did you make it continue clicking on the LCD? I cannot reproduce the corrupted output.
But more importantly, are M0/M1 really supposed to be the same?
The P/S parsing logic also looks completely broken.

I don't want to fix that in this PR, but I'd like to understand what is supposed to do. reprap wiki says marlin hansles m0/m1 the same, but the code makes me think it's buggy.

2022-12-22 14:50 UTC, leptun commented
> Did you make it continue clicking on the LCD

yes
>But more importantly, are M0/M1 really supposed to be the same?
The P/S parsing logic also looks completely broken.
I don't want to fix that in this PR, but I'd like to understand what is supposed to do. reprap wiki says marlin hansles m0/m1 the same, but the code makes me think it's buggy.

Agreed. Maybe we should postpone fixing M0/1 to another PR and just go with the fixed M117.

2022-12-22 14:50 UTC, leptun approved these changes
Approved the changes, but the M0/1 needs to be fixed in another PR.

2022-12-22 15:44 UTC, wavexx commented
> M0/1 needs to be fixed in another PR.

This still needs to work life before though. Do you have some examples of usage?
Trying it here randomly I'm getting the same behavior before/after the PR.

2022-12-26 17:28 UTC, leptun commented
I don't unfortunately. Maybe @3d-gussner or @TojikCZ  have played with this feature before and can give us some examples to test functionality.

2022-12-30 13:06 UTC, merged