🚧 Convert fanSpeed and saved_fan_speed to uint8_t
prusa3d/Prusa-Firmware pull request #3962
Opened 2023-01-27 21:14 UTC by gudnimg

These variables only range from 0 to 255

For the menus we currently need to convert `fanSpeed` to `int16_t`. But globally in the firmware we can keep it one byte.

Change in memory:
Flash: -160 bytes
SRAM: -2 bytes

2023-02-26 21:39 UTC, gudnimg commented
Ran a MMU print with these changes. Print went very smooth and finished on time. Also tested editing the fan speed while printing, works fine as expected.

![image](https://user-images.githubusercontent.com/8218499/221438779-534a766b-c1d5-4047-8022-e56faae57054.jpeg)

2023-03-03 13:42 UTC, leptun commented on Firmware/ultralcd.cpp
> +	MENU_ITEM_EDIT_int3_P(_T(MSG_FAN_SPEED), (int16_t*)&fanSpeed, 0, 255);//5
This needs to be checked carefully. I am suspicious of that int16_t* cast. We need to check that the edit menu doesn't overwrite something around `fanSpeed`.

2023-03-03 13:43 UTC, vintagepc requested changes

2023-03-03 13:43 UTC, vintagepc commented on Firmware/ultralcd.cpp
>  	MENU_ITEM_EDIT_int3_P(_i("Flow"), &extrudemultiply, 10, 999);//6////MSG_FLOW c=15
Yes, this is definitely dangerous. You'll zero the adjacent byte in memory.

2023-03-03 13:43 UTC, vintagepc commented on Firmware/ultralcd.cpp
> +  MENU_ITEM_EDIT_int3_P(_T(MSG_FAN_SPEED), (int16_t*)&fanSpeed, 0, 255);
ditto

2023-03-04 20:34 UTC, gudnimg commented
If we can get that menu change [34c1e55](https://github.com/prusa3d/Prusa-Firmware/pull/3962/commits/34c1e55863650c3859567a2d73283109eefeb9d6) through that would eliminate one annoying edge case in the menu code. I didn't see before that it only affects one menu item.

Gives me more hope of finishing https://github.com/prusa3d/Prusa-Firmware/pull/3985 😆

2023-04-04 16:31 UTC, gudnimg commented
Rebased to sync with MK3 and fix conflict

2023-04-05 15:03 UTC, DRracer commented on Firmware/menu.cpp
> +template void menu_draw_P<uint8_t>(char chr, const char* str, uint8_t val);
removal of the special code for linearity correction has been approved :tada:

2023-04-06 04:06 UTC, merged