MMU: Simplify `T?` processing
prusa3d/Prusa-Firmware pull request #4161
Opened 2023-04-22 15:13 UTC by gudnimg

We can use `bool MMU2::tool_change(char code, uint8_t slot)` to process `T?`. This way we don't need to call `load_filament_to_nozzle()` in `TCodes.cpp`. This also reduces the code complexity quite a bit.

Tested on MK3S+:
* ✅ T0
* ✅ Tx and Tc by starting a print
* ✅ T?
* ✅ Load to Nozzle from LCD

Change in memory:
Flash: -64 bytes
SRAM: 0 bytes

2023-04-22 15:13 UTC, gudnimg commented
Assigning this to 3.13 RC2. I think it's too risk for RC1.

2023-07-13 08:54 UTC, DRracer requested changes
I'm afraid replacing `load_filament_to_nozzle` with a plain `tool_change` is not correct. 

`load_filament_to_nozzle` really pushes filament into the tip of the nozzle while a `tool_change` doesn't.

Or am I missing something?

2023-07-14 11:54 UTC, gudnimg commented
> I'm afraid replacing `load_filament_to_nozzle` with a plain `tool_change` is not correct.
> 
> `load_filament_to_nozzle` really pushes filament into the tip of the nozzle while a `tool_change` doesn't.
> 
> Or am I missing something?

It looks like to me we are currently duplicating the code by handling `T?` in `Tcodes.cpp` and in `tool_change()`

The proposed changes now calls a variant of `tool_change` which handles the `T?` character and calls `load_filament_to_nozzle`. Remember `tool_change` is overloaded.

`MMU2::mmu2.tool_change(strchr_pointer[index], choose_menu_P(_T(MSG_SELECT_FILAMENT), _T(MSG_FILAMENT)));`

2023-08-02 11:30 UTC, gudnimg commented
Marking this with 🚧 as the PR will need to be re-tested to verify it doesnt break edge cases.

2023-08-11 12:31 UTC, 3d-gussner approved these changes
Tested on MK404

2023-08-11 12:31 UTC, DRracer approved these changes

2023-08-11 12:31 UTC, merged