cleanup: more compact code
prusa3d/Prusa-Firmware pull request #4176
Opened 2023-04-29 11:31 UTC by gudnimg

Remove 70 lines of code by making
the gcode/mcode parsing more compact in a few selected places

We can probably do a lot more but this is a small step the right direction.

No change in memory

2023-09-12 15:19 UTC, 3d-gussner reviewed
See comments

2023-09-12 15:19 UTC, 3d-gussner commented on Firmware/Marlin_main.cpp
> +        if(code_seen('S') && strchr_pointer < namestartpos) {
Why `{}` here while other places removed?

2023-09-12 15:19 UTC, 3d-gussner commented on Firmware/Marlin_main.cpp
> +        if(code_seen('S') && strchr_pointer < namestartpos) {
The comment can be above

2023-09-12 15:19 UTC, 3d-gussner commented on Firmware/Marlin_main.cpp
> +      if (code_seen('E')) {
Why not?
if (code_seen('E')) e = code_value_short();
if (e < 0) temp = 70;

2023-09-12 15:22 UTC, DRracer requested changes
While doing such a refactoring, please reformat the code segments according to our code style rules. Especially the "parsing" code is horrible and often mis-indented.

2023-09-16 14:23 UTC, gudnimg commented
Closing this PR, we're probably better of just reformatting the entire file

2023-09-16 14:23 UTC, closed without merging