Fix IRsensor with MMU
prusa3d/Prusa-Firmware pull request #4214
Opened 2023-05-19 11:37 UTC by 3d-gussner

saves 38bytes

2023-05-20 09:46 UTC, gudnimg commented on Firmware/ultralcd.cpp
>      for(uint_least8_t i = 0; i < 200; ++i)
I feel the code below should be deleted as it is part of the old ancient MMU2 test.

2023-05-20 09:46 UTC, gudnimg commented on Firmware/ultralcd.cpp
>      class TempBackup
Please remove this class. We are no longer heating the extruder to some temperature.

2023-05-20 09:48 UTC, gudnimg requested changes
Above are two comments. I feel we should delete the old code since we should really be re-writing the test for the new MMU implementation. The old code is for MMU FW 1.0.6 which we don't support anymore.

2023-05-20 10:43 UTC, gudnimg commented
Here's an easy way to ask the user to select which slot to use for the test:

LCD updates are disabled so the slot selection menu doesn't timeout 👍 

```cpp
static bool selftest_irsensor()
{
    // Ask user which slot to load filament from
    uint8_t slot = choose_menu_P(_T(MSG_SELECT_FILAMENT), _T(MSG_FILAMENT));

    // Render self-test screen
    lcd_selftest_screen(TestScreen::Fsensor, 0, 1, true, 0);

    // Run self-test
    set_extrude_min_temp(0);
    MMU2::mmu2.tool_change(slot);
    MMU2::mmu2.unload(); //Unload filament
    set_extrude_min_temp(EXTRUDE_MINTEMP);
    return true;
}
```

2023-05-23 14:54 UTC, 3d-gussner commented
@gudnimg Please review the PR again. Thanks

2023-05-23 19:13 UTC, gudnimg approved these changes
Looks good to me👍

2023-05-24 04:57 UTC, merged