Add new message `Preload to MMU` to po files
prusa3d/Prusa-Firmware pull request #4222
Opened 2023-05-22 07:44 UTC by 3d-gussner

Initial translation

Has to be reviewed by translators

- [ ] CS @DRracer 
- [ ] DE
- [ ] ES
- [ ] FR
- [ ] HR @Prime1910 
- [ ] HU @AttilaSVK @Hauzman
- [ ] IT @wavexx 
- [ ] NL @vintagepc @stelgenhof
- [ ] NO @OS-kar @trondkla
- [ ] PL
- [ ] RO @leptun @Hauzman
- [ ] SK @ingbrzy @shatter136
- [ ] SV @Painkiller56

2023-05-22 07:49 UTC, Prime1910 commented
Croatian looks good :)

2023-05-22 07:51 UTC, trondkla commented
(_no) Norwegian looks good. Would "Forhåndslast MMU" be better Norwegian @OS-kar ?

2023-05-22 07:59 UTC, arekm commented
For Polish I see "ł" used in po file, so

Zaladuj do MMU -> Załaduj do MMU

2023-05-22 08:09 UTC, shatter136 commented
In SK, the translation is now Czech, so correct should perhaps be "Predzásobenie"

2023-05-22 08:13 UTC, AttilaSVK commented
Hi! Hungarian should be "Betöltés az MMU-ba"

3d-gussner ***@***.***> ezt írta (időpont: 2023. máj. 22., H,
9:44):

> Initial translation
>
> Has to be reviewed by translators
>
>    - CS @DRracer <https://github.com/DRracer>
>    - DE
>    - ES
>    - FR
>    - HR @Prime1910 <https://github.com/Prime1910>
>    - HU @AttilaSVK <https://github.com/AttilaSVK> @Hauzman
>    <https://github.com/Hauzman>
>    - IT @wavexx <https://github.com/wavexx>
>    - NL @vintagepc <https://github.com/vintagepc> @stelgenhof
>    <https://github.com/stelgenhof>
>    - NO @OS-kar <https://github.com/OS-kar> @trondkla
>    <https://github.com/trondkla>
>    - PL
>    - RO @leptun <https://github.com/leptun> @Hauzman
>    <https://github.com/Hauzman>
>    - SK @ingbrzy <https://github.com/ingbrzy> @shatter136
>    <https://github.com/shatter136>
>    - SV @Painkiller56 <https://github.com/Painkiller56>
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/prusa3d/Prusa-Firmware/pull/4222
> Commit Summary
>
>    - 3c22945
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/commits/3c229453cec1daf7ccc244bb50a5d770c9d0bdaa>
>    Add new message `Preload to MMU` to po files
>
> File Changes
>
> (14 files <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files>)
>
>    - *M* lang/po/Firmware.pot
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-14fedb8dfdce511a0bdcf251bbe0fc1c53d69fcec094186519cc6f57826b4b1b>
>    (5)
>    - *M* lang/po/Firmware_cs.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-0aa4aafa0e88956cdefd904d3a4d90d8075a6baea4b7a7552fa25663b8550f7c>
>    (5)
>    - *M* lang/po/Firmware_de.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-7aa3bbee27c68325a9362a2508a9dbdffb40452a4296772d7b6075b7cafd7d43>
>    (5)
>    - *M* lang/po/Firmware_es.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-94fdeb509cca7d35e68df03af06931c6c67805acb0c427946922c1b5caa91549>
>    (5)
>    - *M* lang/po/Firmware_fr.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-e1c029266b2a50654a6638406d3cfe838eeb4502bde0aadca6cdcb4372d42a44>
>    (5)
>    - *M* lang/po/Firmware_hr.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-487d5469566575627c7dc47abf437c52e890de941c1fd8d4db5a2a4d6ef08d64>
>    (5)
>    - *M* lang/po/Firmware_hu.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-3a7d51d07fb16c60d273b7986aa88a7892939b19a9bad4f3501a153ffb0604e9>
>    (5)
>    - *M* lang/po/Firmware_it.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-d948679300ec3cbaa7e705150dfcaee8932cf6f047e800ca1036ff551f31e81c>
>    (5)
>    - *M* lang/po/Firmware_nl.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-92de134d7cfe75b62e86a4e83716cd95550b11f2ddee228150a9c6faa4d6a34b>
>    (5)
>    - *M* lang/po/Firmware_no.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-22e5dd5d54111e837f3b40db65f2a126b09cc4157dcfa1f34b6e5dde0bf4a607>
>    (5)
>    - *M* lang/po/Firmware_pl.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-67132bccb4c23fbeaf41753633298c3047956124c6a42a0a8a574e3c042a09e0>
>    (5)
>    - *M* lang/po/Firmware_ro.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-6774f424618c20ccb1d99bf93cb34bab0b6ee03a55868fa7021a11ef6c28667f>
>    (5)
>    - *M* lang/po/Firmware_sk.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-9584ba5c6a2b7618c16dc96fa21d692e9d5d69c393c55f37166bb05e98557fbc>
>    (5)
>    - *M* lang/po/Firmware_sv.po
>    <https://github.com/prusa3d/Prusa-Firmware/pull/4222/files#diff-cf46655e0192f28112da2985d28dc728949010730a0ac629dbb7049f9f53a357>
>    (5)
>
> Patch Links:
>
>    - https://github.com/prusa3d/Prusa-Firmware/pull/4222.patch
>    - https://github.com/prusa3d/Prusa-Firmware/pull/4222.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prusa3d/Prusa-Firmware/pull/4222>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIZ6Q5OQFLOUTX2FCONEHYDXHMKOLANCNFSM6AAAAAAYKBDBTI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-22 08:23 UTC, leptun commented
RO looks good

2023-05-22 08:25 UTC, 3d-gussner commented
> orhåndslast

Issue is that it limited to 17 chars

2023-05-22 08:34 UTC, 3d-gussner commented
> Betöltés az MMU-ba

It is 18 char but we are limited to 17 what is the best to shorten it?

2023-05-22 08:36 UTC, AttilaSVK commented
Just leave out the hyphen: Betöltés az MMUba

3d-gussner ***@***.***> ezt írta (időpont: 2023. máj. 22., H,
10:34):

> Betöltés az MMU-ba
>
> It is 18 char but we are limited to 17 what is the best to shorten it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prusa3d/Prusa-Firmware/pull/4222#issuecomment-1556781809>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIZ6Q5JSYJK6V5GZQ3AVTQ3XHMQKBANCNFSM6AAAAAAYKBDBTI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-22 08:49 UTC, shatter136 approved these changes
Ok now

2023-05-22 08:51 UTC, SNDR0 commented
In italian will be better "Caricamento MMU" , if we consider the mmu like a magazine.. or "Precaricamento MMU" if you want to translate from English...

2023-05-22 08:54 UTC, 3d-gussner commented
> In italian will be better "Caricamento MMU" , if we consider the mmu like a magazine.. or "Precaricamento MMU" if you want to translate from English...

@SNDR0 :bow:  Thanks for the suggestion I will forward that to the internal translators.

2023-05-22 10:37 UTC, stelgenhof requested changes

2023-05-22 10:37 UTC, stelgenhof commented on lang/po/Firmware_nl.po
> +msgstr "Preload naar MMU"
I would suggest to change it to "Voorladen in MMU".

2023-05-22 12:08 UTC, Painkiller56 commented
Swedish looks good.

2023-05-22 14:43 UTC, 3d-gussner commented
> In italian will be better "Caricamento MMU" , if we consider the mmu like a magazine.. or "Precaricamento MMU" if you want to translate from English...

@SNDR0 :bow:  Thanks for the suggestion I will forward that to the internal translators.

2023-05-22 17:40 UTC, wavexx commented
> In italian will be better "Caricamento MMU" , if we consider the mmu like a magazine.. or "Precaricamento MMU" if you want to translate from English...

From the context, I'd go for "Precarica MMU", and maybe also change "Carica tutti" to "Precarica tutti" for consistency. What do you think @SNDR0 ?

2023-05-22 17:45 UTC, SNDR0 commented
Wonderful... Nothing to add...

2023-05-23 00:33 UTC, trfunk commented
I would suggest "In MMU laden" for german, it's similar to the "load to nozzle" msg then and "vorladen" isn't really used.

2023-05-23 06:37 UTC, 3d-gussner commented
> I would suggest "In MMU laden" for german, it's similar to the "load to nozzle" msg then and "vorladen" isn't really used.

Thanks! 
Dankeschön, habe Deine Übersetzung übernommen. Gut gesehen das andere ähnlich sind.

2023-05-23 06:41 UTC, 3d-gussner commented
> and maybe also change "Carica tutti" to "Precarica tutti" for consistency. 

Issue is that `Load all` is used twice and other translations are still based on that term.
I will ask if we should change `Load all` to `Preload all`.

2023-05-23 09:52 UTC, SNDR0 commented
Last question... Isn't better write "Preload MMU"?

2023-05-23 10:06 UTC, DRracer commented
@SNDR0 "Preload MMU" would also make sense, but IMO "Preload to MMU" is more explicit, that we want to put the filament into the MMU (and not into the printer)

2023-05-23 15:02 UTC, Janys commented
@3d-gussner @DRracer Czech: "Zavést do MMU"

2023-05-23 15:23 UTC, 3d-gussner commented
Thanks to everyone for fast review :hugs:

2023-05-23 22:14 UTC, gudnimg approved these changes

2023-05-24 04:57 UTC, merged