MEGRE dependecies: Set Ready translations
prusa3d/Prusa-Firmware pull request #4430
Opened 2023-10-05 13:19 UTC by 3d-gussner

Don't merge before #4429

Please ignore during review the /Firmware/*.* files these are part of #4429. I hope splitting the PR in two parts prevents conflicts with other existing PRs.

- :czech_republic: :heavy_check_mark: from PrusaConnect
- :de: :heavy_check_mark: from PrusaConnect
- :es: :heavy_check_mark: from PrusaConnect
- :fr:  :heavy_check_mark: from PrusaConnect
- :it: :heavy_check_mark: from PrusaConnect had to shorten it to fit
- :poland: :heavy_check_mark: from PrusaConnect
- :netherlands: :heavy_check_mark: translated by @3d-gussner. Please check @vintagepc 
- :romania: Please check @leptun and @Hauzman
- :hungary: Please check @@AttilaSVK and @Hauzman 
- :croatia: Please check @Prime1910
- :slovakia: Please check @ingbrzy and @shatter136
- :svalbard_jan_mayen: Please check @Painkiller56
- :norway: Please check @OS-kar and @trondkla

2023-10-05 19:53 UTC, trondkla commented
Norwegian is Good

2023-10-05 20:20 UTC, leptun commented on lang/po/Firmware_ro.po
> +msgstr "Set pregătit"
This is wrong. The translation used the meaning of "set" as in "a set of items", which is wrong.
"Printer pregătit" might be better in this context, but it's still not that great.

2023-10-05 20:23 UTC, vintagepc approved these changes

2023-10-06 07:08 UTC, shatter136 requested changes
I would not use "Pripravte sa" for "Set ready". It seems it means something like "Set printer as ready"  Is that correct? In such case the best would be "Nastaviť ako pripravené". However, I see Czech translation is "Připravit". So if it must be shorter message, Slovak could be "Pripraviť" or "Pripravené"

2023-10-06 08:30 UTC, ingbrzy commented on lang/po/Firmware_sk.po
> +msgstr "Pripravte sa"
Should be "Pripravené"

2023-11-19 09:40 UTC, gudnimg requested changes
This PR seems to conflict with https://github.com/prusa3d/Prusa-Firmware/pull/4429 for non-translation specific changes.

2023-11-19 09:40 UTC, gudnimg commented on Firmware/cmdqueue.cpp
> +            printer_state = 3; //set printer state busy printing to hide LCD menu and report correctly M862.7 Q while USB printing
This conflicts with https://github.com/prusa3d/Prusa-Firmware/pull/4429

2023-11-19 09:40 UTC, gudnimg commented on Firmware/Marlin_main.cpp
> +                    break;
I think this should be in https://github.com/prusa3d/Prusa-Firmware/pull/4429 it's missing the `~.7`?

2023-11-21 14:07 UTC, 3d-gussner commented
Add all translation to https://github.com/prusa3d/Prusa-Firmware/pull/4429

2023-11-21 14:07 UTC, closed without merging