Add max acceleration mm per s2, feedrates and jerk save and restor du…
prusa3d/Prusa-Firmware pull request #4657
Opened 2024-04-09 16:45 UTC by 3d-gussner

…ring power panic

Thanks to @wavexx in #2456

2024-04-09 17:20 UTC, gudnimg commented
Using  `eeprom_update_block` instead of four 4x `eeprom_update_float` will save a lot of flash. It’s not faster though, I wonder how much time all of these EEPROM writes add to the power panic. 

Quick look at the datasheet for ATmega2560 gives typical EEPROM write time 3.3ms. 60 bytes is ~200ms… assuming its 3.3ms per byte 🤔

2024-04-10 08:20 UTC, 3d-gussner commented
>It’s not faster though, I wonder how much time all of these EEPROM writes add to the power panic.
Quick look at the datasheet for ATmega2560 gives typical EEPROM write time 3.3ms. 60 bytes is ~200ms… assuming its 3.3ms per byte 🤔

Tested on MK404
- Operating printer with normal PrusaSlicer profile
  - PowerPanic reports `UVLO - end 164` which is ~164ms (on MK404 not real printer)
- Factory reset printer with normal PrusaSlicer profile 
  - PowerPanic reports `UVLO - end 165` which is ~165ms (on MK404 not real printer)

Also these values are stored with `M500` in eeprom, so as long the print profiles don't change a lot I expect not a big increase of time needed while power panic.

Also checked the PrusaSlicer-settings and the Machine limits values didn't change as far I can tell.

Another test with multiple changes in the gcode setting different  jerk, accel and feedrates increased to `UVLO - end 180` (on MK404 not real printer)

If we want to save these values we need to deal with the time delay when these settings are different to previous eeprom values.

The eeprom_update still costs some `ms` as it has to read the eeprom and verify if it changed.


@gudnimg Thanks for the hint with `eeprom_update_block_notify` saved 800 bytes of flash.

2024-04-10 08:31 UTC, gudnimg commented
> Also these values are stored with M500 in eeprom, so as long the print profiles don't change a lot I expect not a big increase of time needed while power panic.

Thats a good point. I forgot yesterday that the update functions only do EEPROM write if the value has changed 👍

2024-04-14 11:39 UTC, gudnimg commented on Firmware/eeprom.h
> +| 0x0C6D 3181 | float   | EEPROM_UVLO_ACCELL_MM_S2_NORMAL       | ???          | ff ff ff ffh          | Power Panic acceleration mm per s2 normal         | Power Panic  | D3 Ax0c6d C16
Change `float` to `uint32`

2024-04-14 11:39 UTC, gudnimg commented on Firmware/eeprom.h
> +| 0x0C5D 3165 | float   | EEPROM_UVLO_ACCELL_MM_S2_SILENT       | ???          | ff ff ff ffh          | Power Panic acceleration mm per s2 silent         | Power Panic  | D3 Ax0c5d C16
Change `float` to `uint32`

2024-04-14 11:40 UTC, gudnimg commented on Firmware/eeprom.h
> +#define EEPROM_UVLO_ACCELL_MM_S2_SILENT (EEPROM_UVLO_ACCELL_MM_S2_NORMAL-4*4) // 4 x float
Change `float` to `uint32`

2024-04-14 11:40 UTC, gudnimg commented on Firmware/eeprom.h
> +#define EEPROM_UVLO_MIN_SEGMENT_TIME_US (EEPROM_UVLO_MIN_TRAVEL_FEEDRATE-4) //unit32_t
typo, unit32_t --> uint32_t

2024-04-14 11:42 UTC, gudnimg commented on Firmware/power_panic.cpp
> +    // Save Jerk
Just my opinion, but I feel these comments aren't useful:

```
// Save min extrude temp
// Save max acceleration mm per s2
// Save feedrates
// Save Jerk
```

I would remove them as the variable names themselves tell me the same information

2024-04-14 11:44 UTC, gudnimg commented on Firmware/power_panic.cpp
> +    eeprom_read_block(cs.max_jerk, (float *)EEPROM_UVLO_MAX_JERK, sizeof(cs.max_jerk));
Similar to another comment of mine, are these comments really useful?

```
// Recover min extrude temp
// Recover max acceleration mm per s2
// Recover feedrates
// Recover jerk
```

2024-04-14 11:50 UTC, gudnimg requested changes
PR looks good to me, just some minor typos that need fixing

2024-04-15 05:29 UTC, 3d-gussner commented
> PR looks good to me, just some minor typos that need fixing

@gudnimg Thanks for the review, gonna fix the typos

2024-04-15 07:36 UTC, gudnimg approved these changes

2024-04-15 13:11 UTC, merged