Use M70 to set label for the filament to load at the M600 Insert filament screen
prusa3d/Prusa-Firmware pull request #4731
Opened 2024-07-26 20:08 UTC by Panayiotis-git

A variation of the https://github.com/prusa3d/Prusa-Firmware/pull/4548. It repurposes the unused M70 command in the Prusa firmware to store a custom message, which is displayed by the M600 command on the load filament screen.

```
M70 Deep Blue
M600
```
The Insert filament screen will then show the custom text defined with the M70 command:
```
Insert filament
Deep Blue
and press the knob
```

2024-07-26 20:27 UTC, gudnimg requested changes
Hi thanks for the PR. The only problem I see (at least on Github) is inconsistent indentation changes in the code. I commented on only two of them but there are more.

It could be a mix between spaces and tabs that makes the rendering different on Github.

2024-07-26 20:27 UTC, gudnimg commented on Firmware/ultralcd.cpp
> +    }
Something is off with indentation here.

2024-07-26 20:27 UTC, gudnimg commented on Firmware/ultralcd.cpp
> +    UnconditionalStop();
Indentation was correct before.

2024-07-26 20:32 UTC, Panayiotis-git commented
Something is really off...

2024-07-26 20:50 UTC, gudnimg commented
Much better, thanks!

2024-07-26 20:53 UTC, gudnimg approved these changes
Code looks good to me. I don’t see how it can go wrong. Should be tested on hardware though before merging, just in case.

2024-07-28 16:44 UTC, gudnimg commented
I tested this on my MK3S+ and I didn't find any way to break things :)

* Sending only `M70` shows no message ✔️ 
* Sending `M70 "Hello World"` shows `"Hello World"` including the " characters ✔️ Exactly like M117
* Running `M600` the 2nd time (but not `M70`), no message is shown indicating it's reset properly. ✔️ 

If no one objects to this PR, I would like to merge it.

2024-08-22 12:13 UTC, 3d-gussner commented
Closing in favor of https://github.com/prusa3d/Prusa-Firmware/pull/4759

2024-08-22 12:13 UTC, closed without merging