Update language_de.h
prusa3d/Prusa-Firmware pull request #519
Opened 2018-03-05 14:08 UTC by Xillius178

Why do yo use not the German "Umlaute" ä ü ö ???

So i have corrected some wrong words.

Hope this ist helpful for you.

Greetings Martin aka Xillius178

2018-03-05 15:01 UTC, GurliGebis commented
Might be that the font the LCD is using doesn't have them? (Not sure, just guessing)

2018-03-05 15:21 UTC, Xillius178 commented
That can be, depending on which library is used,

2018-03-05 15:22 UTC, Xillius178 commented
The Code on the last of this Homepage could help:
http://www.mathias-wilhelm.de/arduino/beginner/schritt-6-lcd-displays/

2018-03-05 16:53 UTC, AnHardt commented
Usually the display on the `REPRAP_DISCOUNT_SMART_CONTROLLER` is a HITACHI `HD44780` in the Japanese font version. (https://www.sparkfun.com/datasheets/LCD/HD44780.pdf page 17)
'ä' = 0xE1, 'ö' = 0xEF, and a mixture between 'ü' and 'Ü' = 0xF5. 'beta' can be used as 'ß' = 0xE2. 'Ä' and 'Ö' are not available.
You could use that but it will break the compatibility with all the graphic displays.
In the language files you have to use the hex numbers. Usually your text editor (including Arduino IDE) will produce 2 byte UTF8 sequences. They will be seen as two strange glyphs.

2018-08-07 22:27 UTC, benderl requested changes

2018-08-07 22:27 UTC, benderl commented on Firmware/language_de.h
> +	+ #define MSG_SD_OPENROOT_FAIL                "Zugriff auf Basisverzeichnis Misslungen"
"misslungen" is not a noun and must not be written with a capital m.

2018-08-07 22:27 UTC, benderl commented on Firmware/language_de.h
> +	+ #define MSG_SD_WORKDIR_FAIL                 "Oeffnen Arbeitsverzeichnis Misslungen"
Same as above. No capital m here.

2018-08-07 22:27 UTC, benderl commented on Firmware/language_de.h
> +	+ #define MSG_SD_OPEN_FILE_FAIL               "Fehler beim oeffnen der Datei: "
Here "Öffnen" has a capital O.

2018-08-07 22:27 UTC, benderl commented on Firmware/language_de.h
> +#define MSG_WIZARD							"Erste Schritte Assistent"
I would suggest just "Assistent".

2018-08-08 04:01 UTC, 3d-gussner commented
I did some language adjustments and added some other and what you have to watch out is the limited space and location on the LCD. So you have to watch out even if you translate things right they might not fit and will fail on the screen. Long texts aren't the issue as they scroll but even here you have to remember how it looks on that LCD. Sometimes it makes more sense to split words to make it readable otherwise you get few lines with just one or two words, which isn't pleasant to read and follow the instructions.

It is a pity that Prusa didn't use the LCD with western European ROM as they sell that much printers. In German you can write ö,ü,ä,β as oe,ue,ae,ss and will be understood by German speaking users, but French/Spanish/Portuguese/Swedish often don't have a different way to write it and makes it odd to read.

2019-09-10 10:45 UTC, 3d-gussner commented
@Xillius178 This PR have been inactive for long time, can you please close it? Or does it still makes sense?

2019-10-08 17:50 UTC, 3d-gussner commented
@DRracer no reaction from owner, guess it is outdated and can be closed.

2019-10-25 16:53 UTC, 3d-gussner commented
@michalxfanta No reaction from owner, guess it is outdated and can be closed.

2020-05-14 09:24 UTC, closed without merging