Polish language updated
prusa3d/Prusa-Firmware pull request #87
Opened 2017-05-03 09:58 UTC by q3ok

Fixed grammar mistakes and some typos

2017-05-08 20:57 UTC, michalzielanski commented
Zmień jeszcze `"Przodni went. Druku?"` na `"Przedni went. druku?"` w `MSG_SELFTEST_COOLING_FAN`.

2017-09-04 11:31 UTC, qbah91 requested changes
Line 15 - "Wystudzić" instead of "Wychlodzic"
Lines 203&204 - "krańców" instead of "krancowek"
Line 255 - "Prosze obracaj pokrętłem poki znacznik nie dosiegnie obudowy ekstrudera. Potwierdz wciskajac przycisk" instead of "Prosze krecic guzik poki znacznik nie dosiegnie ciala ekstrudera. Potwierdzic przyciskiem."

2019-09-10 10:42 UTC, 3d-gussner commented
@q3ok This PR have been inactive for long time, can you please close it?

2019-10-08 17:46 UTC, 3d-gussner commented
@DRracer no reaction from owner, guess it is outdated and can be closed.

2019-10-25 16:48 UTC, 3d-gussner commented
@michalxfanta No reaction from owner, guess it is outdated and can be closed.

2020-05-14 09:22 UTC, closed without merging